version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    restart: always

  app:
    build: .
    container_name: app-mysql
    command: ["dockerize", "-wait", "tcp://mysql-db:3306", "-timeout", "20s", "python", "/app/api.py"]
    ports:
      - "4000:4000"
    depends_on:
      - mysql-db
    restart: always

volumes:
  mysql-data:
    name: mysql-data