# Generated by Django 4.2.6 on 2023-10-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
