# Generated by Django 4.2.6 on 2023-10-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
                ('work_place', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kids', models.ManyToManyField(related_name='parents', to='person.parent')),
            ],
            bases=('person.person',),
        ),
    ]
