# Generated by Django 4.2.6 on 2023-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='kids',
            field=models.ManyToManyField(null=True, related_name='parents', to='person.parent'),
        ),
    ]
