# Generated by Django 4.2.6 on 2023-10-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_parent_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='kids',
            field=models.ManyToManyField(blank=True, related_name='parents', to='person.parent'),
        ),
    ]
