# Generated by Django 4.2.6 on 2023-10-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_parent_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='kids',
            field=models.ManyToManyField(blank=True, null=True, related_name='kids', to='person.person'),
        ),
    ]
