# Generated by Django 4.2.6 on 2023-10-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='is_read',
        ),
    ]
