# Generated by Django 4.2.6 on 2023-10-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
