# Generated by Django 4.2.6 on 2023-10-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='message.chat'),
        ),
    ]
