# Generated by Django 4.2.6 on 2023-10-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('attack_priority', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('enemy_organization', models.CharField(max_length=255)),
                ('target_goal', models.CharField(max_length=255)),
                ('was_target_destroyed', models.BooleanField()),
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
