# Generated by Django 4.2.6 on 2023-10-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Waiting_Response', 'Waiting Response'), ('Pending', 'Pending')], default='Open', max_length=40)),
                ('related_users', models.ManyToManyField(blank=True, related_name='received_events', to='user.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('upload_date', models.DateField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='EventChat',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('chats', models.ManyToManyField(blank=True, related_name='chats', to='message.chat')),
            ],
            bases=('events.event',),
        ),
    ]
