# Generated by Django 4.2.6 on 2023-10-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
