# Generated by Django 4.2.6 on 2023-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_remove_chat_messages_alter_message_chats'),
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='message.chat'),
        ),
    ]
