# Generated by Django 4.2.6 on 2023-10-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_chats_user_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
    ]
