# Generated by Django 4.2.6 on 2023-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_remove_chat_messages_alter_message_chats'),
        ('user', '0007_remove_user_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, to='message.chat'),
        ),
    ]
