# Generated by Django 4.2.6 on 2023-10-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
