# Generated by Django 4.2.6 on 2023-10-22 13:22

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(validators=[book.models.validate_publish_date]),
        ),
    ]
